version: '3'
services:
  rails:
    build:
      context: .
      dockerfile: ./ruby/Dockerfile
    environment:
      RAILS_ENV: "development"
      POSTGRESQL_USER: "postgres_master"
      POSTGRESQL_PASSWORD: "postgres_password"
      POSTGRESQL_HOST: "postgresql"
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    depends_on:
      - postgresql
    ports:
      - "3000:3000"
    volumes:
      - ./u22_app:/app
      - bundle_data:/usr/local/bundle

  postgresql:
    build:
      context: .
      dockerfile: ./postgresql/Dockerfile
    environment:
      POSTGRES_PASSWORD: "postgres_password"
      POSTGRES_USER: "postgres_master"
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  bundle_data:
  pg_data: